apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: elasticsearch-kibana
  labels:
    app: kibana
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
  - host: logs.mgmt.tkg-vsp-lab.hyrulelab.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
           name: kibana
           port:
             number: 5601
