apiVersion: clusters.tmc.cloud.vmware.com/v1alpha1
kind: Extension
metadata:
  name: harbor
  namespace: tanzu-system-registry
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  description: harbor
  version: "v2.0.2_vmware.1"
  name: harbor
  namespace: tanzu-system-registry
  deploymentStrategy:
    type: KUBERNETES_NATIVE
  objects: |
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: harbor
      annotations:
        tmc.cloud.vmware.com/orphan-resource: "true"
    spec:
      syncPeriod: 5m
      serviceAccountName: harbor-extension-sa
      fetch:
        - image:
            url: registry.tkg.vmware.run/tkg-extensions-templates:v1.2.0_vmware.1
        - inline:
            pathsFrom:
              - configMapRef:
                  name: harbor-overlay
      template:
        - ytt:
            ignoreUnknownComments: true
            paths:
              - 0/tkg-extensions/common
              - 0/tkg-extensions/registry/harbor
              - 1/overlay-s3-pvc-fix.yaml
              - 1/trust-letsencrypt.yaml
            inline:
              pathsFrom:
                - secretRef:
                    name: harbor-data-values
      deploy:
        - kapp:
            rawOptions: ["--wait-timeout=5m"]
