AWS_REGION: # Added by scripts
AWS_SSH_KEY_NAME: # Added by scripts
CLUSTER_NAME: # Added by scripts
OIDC_IDENTITY_PROVIDER_CLIENT_ID: # Added by scripts
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: # Added by scripts
OIDC_IDENTITY_PROVIDER_ISSUER_URL: # Added by scripts
WORKER_MACHINE_COUNT: # Added by scripts

INFRASTRUCTURE_PROVIDER: aws
CLUSTER_PLAN: dev # default is blank
CONTROL_PLANE_MACHINE_TYPE: # Added by scripts by pulling aws.control-plane-machine-type in params.yaml
NODE_MACHINE_TYPE: # Added by scripts by pulling aws.node-machine-type in params.yaml

TKG_HTTP_PROXY_ENABLED: "false" # default is blank
ENABLE_AUDIT_LOGGING: "true"
ENABLE_MHC: "true" # default is blank
ENABLE_CEIP_PARTICIPATION: "false" # default is true
BASTION_HOST_ENABLED: "true" # this is default but good to be explicit
IDENTITY_MANAGEMENT_TYPE: oidc # this is default but good to be explicit

# Following are explicit opinions set for this lab associated for OIDC
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: groups
OIDC_IDENTITY_PROVIDER_NAME: "okta"
OIDC_IDENTITY_PROVIDER_SCOPES: openid,profile,email,groups,offline_access
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: email
