apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-pinniped-cert
  namespace: pinniped-supervisor
spec:
  # Secret names are always required.
  secretName: custom-auth-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject: 
    organizations:
    - vmware
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames: # Populated by scripts
  issuerRef:
    name: letsencrypt-contour-cluster-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer